'use strict';
/*
  Script generated by Robins Gupta
*/
/*
  Sending the push notifation from the Application
*/

//This method returns the push service sendMessage send  method..
module.exports = function(ApplicationModel, NotificationModel, PushModel) {

    let badge = 1;
	/**
     * Send message to user..
	 * @param app
	 * @param message
	 * @param registrationId
	 * @param from
	 * @param callback
	 */
    let sendMessage = function(app, message, registrationId, from, callback) {
        let Application = ApplicationModel;
        let Push = PushModel;
        let Notification = NotificationModel;

        let note = new Notification({
            expirationInterval: 3600 * 24, // Expires 1 hour from now.
            badge: badge++,
            message: message,
            alert: message,
            messageFrom: from
        });


	    Push.notifyById(registrationId, note, function(err) {
            if (err) {
                console.error('Cannot notify %j: %s', registrationId, err.stack);
                return callback(err);

            }
            console.log('Pushing notification to %j', registrationId);
            callback(null, []);
        });
    }; //sendMessage function

    //Returns SendMessage function to send Push message..
    return sendMessage;

};